name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd hello-node
        docker build -t hello-node .
        docker run -d -p 3000:3000 hello-node
        curl http://localhost:3000
